steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "create-env"]
  env:
    - 'API_URL = https://api.cartolafc.globo.com/'
    - 'ID_GROUP_SCC1 = 558198693799-1517851623@g.us'
    - 'ID_GROUP_SCC2 = 558196094216-1435093409@g.us'
    - 'ID_GROUP_TEST = 120363024226263418@g.us'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "api.yaml", "-v", "$_GAE_VERSION"]
timeout: "1600s"